version: 2.1
executors:
  rf-executor:
    docker:
      - image: ubuntu:latest
jobs:
  build:
    environment:
      test: 123
    executor: rf-executor
    steps:
      - checkout
      - run:
          name: "install python3 and pip3"
          command: |
            set +e
            apt update
            python3 --version
            if [ $? -ne 0 ]; then
              echo "No python3 installation found...Installing now..."
              apt install python3.8 -y
            else
              echo "Python3 is available...skipping installtion."
            fi
            pip3 --version
            if [ $? -ne 0 ]; then
              echo "No pip3 installation found...Installing now..."
              apt install python3-pip -y
            else
              echo "pip3 is available...skipping the installation now.."
            fi
            set -e

      - run:
          name: "check rf cli installation"
          command: |
            set +e
            which rflogin
            if [ $? -ne 0 ]; then
              echo "Rapidfort cli is missing...installing now..."
              pip3 install rapidfort==0.0.1.dev194 --extra-index-url https://pypi.rapidfort.com
            fi
            set -e
            echo ${pwd}
            mkdir -p ~/.rapidfort
            cat > ~/.rapidfort/credentials \<< EOF
            [rapidfort-user]
            access_id = RF224ba123dc0143f3ae
            secret_key = 18cb30a160cb4135b55992b163da70004ce0ae0b
            EOF
            cat ~/.rapidfort/credentials
      - run:
          name: "build stub"
          command: |
            echo "This is test...."