version: 2.1
# executors:
#   rf-executor:
#     docker:
#       - image: alpine:latest
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      test: 123
    # executor: rf-executor
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - checkout
      - run:
          name: "install python3 and pip3"
          command: |
            set +e
            apt-get update
            python3 --version
            if [ $? -ne 0 ]; then
              echo "No python3 installation found...Installing now..."
              apt-get install -y python3.8
            else
              echo "Python3 is available...skipping installtion."
            fi
            pip3 --version
            if [ $? -ne 0 ]; then
              echo "No pip3 installation found...Installing now..."
              apt-get install -y python3-pip
            else
              echo "pip3 is available...skipping the installation now.."
            fi
            set -e

      - run:
          name: "check rf cli installation"
          command: |
            set +e
            which rflogin
            if [ $? -ne 0 ]; then
              echo "Rapidfort cli is missing...installing now..."
              pip3 install rapidfort==0.0.1.dev194 --extra-index-url https://pypi.rapidfort.com
            fi
            set -e
            mkdir -p ~/.rapidfort
            cat > ~/.rapidfort/credentials \<< EOF
            [rapidfort-user]
            access_id = RF2a07077bf7ff4bcab1
            secret_key = 46562f3e493b4bf6ba1de157ed421dcd4b868055
            EOF
            cat ~/.rapidfort/credentials
      - run:
          name: "build stub"
          command: |
            set +ex
            which docker
            if [ $? -ne 0 ]; then
              echo "Missing Docker CLI...Installing now..."
              exit 1
            else
              echo "docker CLI is available...Skipping now..."
            fi
            cat ~/.rapidfort/credentials
            echo "------------------------------"
            cat > ~/.rapidfort/credentials \<< EOF
            [rapidfort-user]
            access_id = RF2a07077bf7ff4bcab1
            secret_key = 46562f3e493b4bf6ba1de157ed421dcd4b868055
            EOF
            cat ~/.rapidfort/credentials
            set -ex
            echo "Generating Stub Image"
            docker pull nginx:latest
            docker images
            rfstub nginx:latest