version: 2.1
# executors:
#   rf-executor:
#     docker:
#       - image: alpine:latest
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      API_ROOT_URL: "https://api.rapidfort.com"
      AUTH_SERVER_BASE_URL: "https://auth.rapidfort.com"
      RF_API_SERVER: "https://api.rapidfort.com"
      RF_ACCESS_ID: "RF2a07077bf7ff4bcab1"
      RF_ACCESS_SECRET: "46562f3e493b4bf6ba1de157ed421dcd4b868055"
      DOCKER_TAG: "1.19.6"
    steps:
      # - setup_remote_docker:
      #     version: 19.03.13
      #     docker_layer_caching: false
      - checkout
      - run:
          name: "install python3 and pip3"
          command: |
            set +e
            sudo apt-get update
            python3 --version
            if [ $? -ne 0 ]; then
              echo "No python3 installation found...Installing now..."
              sudo apt-get install -y python3.8
            else
              echo "Python3 is available...skipping installtion."
            fi
            pip3 --version
            if [ $? -ne 0 ]; then
              echo "No pip3 installation found...Installing now..."
              apt-get install -y python3-pip
            else
              echo "pip3 is available...skipping the installation now.."
            fi
            set -e

      - run:
          name: "Setup Rapidfort Environment"
          command: |
            set +e
            which rflogin
            if [ $? -ne 0 ]; then
              echo "Rapidfort cli is missing...installing now..."
              pip3 install rapidfort==0.0.1.dev194 --extra-index-url https://pypi.rapidfort.com
            fi
            set -e
            mkdir -p ~/.rapidfort
            cat > ~/.rapidfort/credentials \<< EOF
            [rapidfort-user]
            access_id = ${RF_ACCESS_ID}
            secret_key = ${RF_ACCESS_SECRET}
            EOF
            cat ~/.rapidfort/credentials
      - run:
          name: "build stub"
          command: |
            set +e
            which docker
            if [ $? -ne 0 ]; then
              echo "Missing Docker CLI...Installing now..."
              exit 1
            else
              echo "docker CLI is available...Skipping now..."
            fi
            set -e
            echo "Generating Stub Image"
            docker pull nginx:${DOCKER_TAG}
            docker images
            rfstub nginx:${DOCKER_TAG}
      - run:
          name: "Run Stub Image"
          command: |
            set +e
            which ab
            if [ $? -ne 0 ]; then
              echo "Missing Apache benchmark utility....Installing now"
              sudo apt-get update
              sudo apt-get install -y apache2-utils
            fi
            set -e
            docker run -dit --cap-add=NET_ADMIN -p 8081:80 nginx:${DOCKER_TAG}-rfstub
            docker ps
            sleep 10
            docker ps
            curl -v http://127.0.0.1:8081/
            docker ps
            set -x
            CONTAINER_ID=`docker ps | grep "nginx:${DOCKER_TAG}-rfstub" | awk '{ print $1 }'`
            if [ -z ${CONTAINER_ID} ]; then
              echo "Container not found"
            else
              echo "Completed testing..Stopping container now..."
              docker container stop ${CONTAINER_ID}
              sleep 10
            fi
            rfdone nginx:${DOCKER_TAG}-rfstub
            set +x
      - run:
          name: "Harden Docker Image"
          command: |
            rfharden nginx:${DOCKER_TAG}-rfstub
      - run:
          name: "Run Harden Image Test"
          command: |
            docker run -dit --cap-add=NET_ADMIN -p 8082:80 nginx:${DOCKER_TAG}-rfhardened
            docker ps
            sleep 10
            docker ps
            curl -v http://127.0.0.1:8082/