version: 2.1
# executors:
#   rf-executor:
#     docker:
#       - image: alpine:latest
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      API_ROOT_URL: "https://api.rapidfort.com"
      AUTH_SERVER_BASE_URL: "https://auth.rapidfort.com"
      RF_API_SERVER: "https://api.rapidfort.com"
      DOCKER_TAG: "1.19.6"
      SLEEP_COUNT: 60 
      DOCKER_IMAGE_NAME: "nginx"
      HOST_PORT: 8080
      APP_PORT: 80
    steps:
      # - setup_remote_docker:
      #     version: 19.03.13
      #     docker_layer_caching: false
      - checkout
      - run:
          name: "install python3 and pip3"
          command: |
            set +e
            sudo apt-get update
            python3 --version
            if [ $? -ne 0 ]; then
              echo "No python3 installation found...Installing now..."
              sudo apt-get install -y python3.8
            else
              echo "Python3 is available...skipping installtion."
            fi
            pip3 --version
            if [ $? -ne 0 ]; then
              echo "No pip3 installation found...Installing now..."
              apt-get install -y python3-pip
            else
              echo "pip3 is available...skipping the installation now.."
            fi
            set -e

      - run:
          name: "Setup Rapidfort Environment"
          command: |
            set +e
            which rflogin
            if [ $? -ne 0 ]; then
              echo "Rapidfort cli is missing...installing now..."
              pip3 install rapidfort --extra-index-url https://pypi.rapidfort.com
            fi
            set -e
            mkdir -p ~/.rapidfort
            cat > ~/.rapidfort/credentials \<< EOF
            [rapidfort-user]
            access_id = ${RF_ACCESS_ID}
            secret_key = ${RF_ACCESS_SECRET}
            EOF
            cat ~/.rapidfort/credentials
      - run:
          name: "build stub"
          command: |
            set +e
            which docker
            if [ $? -ne 0 ]; then
              echo "Missing Docker CLI...Installing now..."
              exit 1
            else
              echo "docker CLI is available...Skipping now..."
            fi
            set -e
            set -x
            echo "Generating Stub Image"
            docker pull ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}
            docker images
            rfstub ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}
      - run:
          name: "Run Stub Image"
          command: |
            set +e
            which ab
            if [ $? -ne 0 ]; then
              echo "Missing Apache benchmark utility....Installing now"
              sudo apt-get update
              sudo apt-get install -y apache2-utils
            fi
            set -e
            echo "Running stub Image now..."
            docker run -dit --cap-add=NET_ADMIN -p ${HOST_PORT}:${APP_PORT} ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}-rfstub

            echo "Waiting for ${SLEEP_COUNT} to container be in running state..."
            sleep ${SLEEP_COUNT}
            CONTAINER_ID=`docker ps | grep "${DOCKER_IMAGE_NAME}:${DOCKER_TAG}-rfstub" | awk '{ print $1 }'`
            if [ -z ${CONTAINER_ID} ]; then
              echo "Container not found"
            else
              echo "sleeping for 20 seconds"
              sleep 20
              echo "Running test now..."
              curl -v http://127.0.0.1:${HOST_PORT}/
              if [ $? -ne 0 ]; then
                echo "Test failed...please check and try again."
                echo "Exiting now..."
              else
                echo "Test succeded..."
              fi
              echo "Completed testing..Stopping container now..."
              docker container stop ${CONTAINER_ID}
              sleep ${SLEEP_COUNT}
            fi
            echo "Running rfdone..."
            rfdone ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}-rfstub
            if [ $? -ne 0 ]; then
              echo "failed to complete rfdone for ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}-rfstub...Please check and try again..."
              exit 1
            else
              echo "Completed process for running stub for ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}-rfstub"
            fi
      - run:
          name: "Harden Docker Image"
          command: |
            echo "Hardening Docker image now..."
            rfharden ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}-rfstub
            if [ $? -ne 0 ]; then
              echo "Failed to harden the docker image ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}-rfhardened... Please check the error and try again..."
              exit 1
            else
              echo "Docker Image hardened ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}-rfhardened"
            fi
      - run:
          name: "Run Harden Image Test"
          command: |
            echo "Running docker image to test the resutl after hardening the docker image"
            docker run -dit --cap-add=NET_ADMIN -p ${HOST_PORT}:${APP_PORT} ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}-rfhardened
            echo "Waiting for ${SLEEP_COUNT} to container in running state."
            sleep ${SLEEP_COUNT}
            echo "Checking for the container state now..."
            CONTAINER_ID=`docker ps | grep "${DOCKER_IMAGE_NAME}:${DOCKER_TAG}-rfhardened" | awk '{ print $1 }'`
            if [ -z ${CONTAINER_ID} ]; then
              echo "Container is not in running state...exiting now..."
              exit 1
            else
              echo "Container with ID ${CONTAINER_ID} is in running state. Running test now..."
              curl -v http://127.0.0.1:${HOST_PORT}/
              if [ $? -ne 0 ]; then
                echo "Test failed..."
              else
                echo "Test passed...Docker image is ready to push to artifactory..."
              fi
            fi