version: 2.1
executors:
  rf-executor:
    docker:
      - image: alpine:latest
jobs:
  build:
    environment:
      test: 123
    executor: rf-executor
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - checkout
      - run:
          name: "install python3 and pip3"
          command: |
            set +e
            apk update
            python3 --version
            if [ $? -ne 0 ]; then
              echo "No python3 installation found...Installing now..."
              apk add python3
            else
              echo "Python3 is available...skipping installtion."
            fi
            pip3 --version
            if [ $? -ne 0 ]; then
              echo "No pip3 installation found...Installing now..."
              apk add py3-pip
            else
              echo "pip3 is available...skipping the installation now.."
            fi
            set -e

      - run:
          name: "check rf cli installation"
          command: |
            set +e
            which rflogin
            if [ $? -ne 0 ]; then
              echo "Rapidfort cli is missing...installing now..."
              pip3 install rapidfort==0.0.1.dev194 --extra-index-url https://pypi.rapidfort.com
            fi
            set -e
            echo ${pwd}
            mkdir -p ~/.rapidfort
            cat > ~/.rapidfort/credentials \<< EOF
            [rapidfort-user]
            access_id = RF224ba123dc0143f3ae
            secret_key = 18cb30a160cb4135b55992b163da70004ce0ae0b
            EOF
            cat ~/.rapidfort/credentials
      - run:
          name: "build stub"
          command: |
            set -e
            which docker
            if [ $? -ne 0 ]; then
              echo "Missing Docker CLI...Installing now..."
              apk add docker-cli
            else
              echo "docker CLI is available...Skipping now..."
            fi
            echo "Generating Stub Image"
            docker pull nginx:latest
            rfstub nginx:latest